# Generated by Django 4.2.29 on 2026-04-16 05:29

import apps.video_streaming.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.video_streaming.models.stream_video_thumbnail_upload_to)),
                ('original_video', models.FileField(blank=True, help_text='Source file (e.g. MP4). Not exposed via public API; transcoded to HLS only.', upload_to=apps.video_streaming.models.stream_video_original_upload_to)),
                ('hls_path', models.URLField(blank=True, default='', help_text='Public playlist URL (index.m3u8) after processing.', max_length=2048)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='processing', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
