# Generated by Django 4.2.29 on 2026-04-16 06:10

import apps.video_streaming.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional. Shown on the Programs grid; falls back to the first video thumbnail.', null=True, upload_to=apps.video_streaming.models.stream_playlist_cover_upload_to)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StreamPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='video_streaming.streamplaylist')),
                ('stream_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='video_streaming.streamvideo')),
            ],
            options={
                'ordering': ['playlist', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='streamplaylistitem',
            constraint=models.UniqueConstraint(fields=('playlist', 'stream_video'), name='video_streaming_playlist_unique_video'),
        ),
    ]
