# Generated by Django 4.2.29 on 2026-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0002_streamplaylist_streamplaylistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamvideo',
            name='show_in_membership',
            field=models.BooleanField(db_index=True, default=False, help_text='Visible in Membership section secure videos.'),
        ),
        migrations.AddField(
            model_name='streamvideo',
            name='show_in_programs',
            field=models.BooleanField(db_index=True, default=True, help_text='Visible in Programs section secure video lists/playlists.'),
        ),
    ]
