# Generated by Django 4.2 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_streaming", "0005_streamvideo_player_layout_and_source_dims"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamplaylist",
            name="category",
            field=models.CharField(
                choices=[
                    ("business_model", "Business Model"),
                    ("business_psychology", "Business Psychology"),
                ],
                db_index=True,
                default="business_psychology",
                help_text="Programs grouping used by dashboard filters.",
                max_length=32,
            ),
        ),
    ]
