# Generated by Django 4.2 on 2026-04-23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_streaming", "0006_streamplaylist_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamplaylist",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Playlist price shown on Programs cards.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="streamplaylist",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Public rating out of 5 stars.",
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
