# Generated by Django 4.2.29 on 2026-03-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=512)),
                ('stored_path', models.CharField(max_length=1024)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('text_extracted', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MindsetKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mindset', to='api.uploadeddocument')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='api.uploadeddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
