# Generated by Django 4.2.29 on 2026-03-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedchallenge',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='generatedchallenge',
            name='challenge_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedchallenge',
            name='difficulty',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='generatedchallenge',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedchallenge',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='generatedchallenge',
            name='mood',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
