# Generated by Django 4.2.29 on 2026-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_challenge_categories_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('creator_device', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemer_device', models.CharField(blank=True, max_length=128)),
                ('restore_claimed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
