# Generated by Django 4.2.29 on 2026-04-15 13:57

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video_url_remove_vdocipher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Programs grid cover. Use a high-resolution file (e.g. JPEG/PNG at least ~1200px on the short edge, or 1600px+ wide) so it stays sharp on retina screens; small images are stretched and look soft.', null=True, upload_to=apps.courses.models.course_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional. Shown in the lesson list.', null=True, upload_to=apps.courses.models.video_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Direct file URL (MP4/WebM) or a normal watch link (e.g. YouTube). Set in Django admin.', max_length=2048),
        ),
    ]
