# Generated by Django 4.2.29 on 2026-04-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_cover_image_alter_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_in_programs',
            field=models.BooleanField(db_index=True, default=True, help_text='If False, this course is hidden from the dashboard Programs grid (lessons API unchanged).'),
        ),
    ]
