"""
Django settings for syndicate_backend project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import quote_plus

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (handles UTF-8 BOM; also try cwd for alternate shells).
# override=False: real process env (e.g. Railway DATABASE_URL) must not be replaced by a stray .env.
for _env_path in (BASE_DIR / ".env", Path.cwd() / ".env"):
    if _env_path.is_file():
        load_dotenv(_env_path, override=False, encoding="utf-8-sig")
        break
else:
    load_dotenv(encoding="utf-8-sig")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-whr8w($+2y))zuz-azy2gr3897!ypihga1tzm$k06%m0&gaf-m")

# SECURITY WARNING: don't run with debug turned on in production!
_default_debug = "false" if (os.environ.get("RAILWAY_ENVIRONMENT") or "").strip() else "true"
DEBUG = os.environ.get("DJANGO_DEBUG", _default_debug).strip().lower() in ("1", "true", "yes")

_allowed = ["localhost", "127.0.0.1"]
for _h in (os.environ.get("ALLOWED_HOSTS") or "").split(","):
    _h = _h.strip()
    if _h and _h not in _allowed:
        _allowed.append(_h)
_railway_host = (os.environ.get("RAILWAY_PUBLIC_DOMAIN") or "").strip()
if _railway_host and _railway_host not in _allowed:
    _allowed.append(_railway_host)
ALLOWED_HOSTS = _allowed

OPENAI_API_KEY = (os.environ.get("OPENAI_API_KEY") or "").strip().strip("\ufeff")
OPENAI_MODEL = (os.environ.get("OPENAI_MODEL") or "gpt-4o-mini").strip()

USE_CLOUDINARY = bool(
    (os.environ.get("CLOUDINARY_URL") or "").strip()
    or (
        (os.environ.get("CLOUDINARY_CLOUD_NAME") or "").strip()
        and (os.environ.get("CLOUDINARY_API_KEY") or "").strip()
        and (os.environ.get("CLOUDINARY_API_SECRET") or "").strip()
    )
)


def _s3_object_storage_config() -> dict | None:
    """S3-*compatible* object storage: Railway Bucket, R2, Tigris, AWS S3, etc. (endpoint chooses the host)."""
    if (os.environ.get("USE_S3_OBJECT_STORAGE") or "").strip().lower() in ("0", "false", "no", "off"):
        return None
    # Railway Buckets: BUCKET, ACCESS_KEY_ID, SECRET_ACCESS_KEY, ENDPOINT, REGION (see railway.com/docs — Storage Buckets).
    # AWS SDK preset on Railway maps many of these to AWS_*; we accept both.
    railway_bucket = (os.environ.get("BUCKET") or "").strip()
    bucket = (
        (os.environ.get("AWS_STORAGE_BUCKET_NAME") or "").strip()
        or (os.environ.get("S3_BUCKET_NAME") or "").strip()
        or railway_bucket
    )
    access = (
        (os.environ.get("AWS_ACCESS_KEY_ID") or "").strip().strip("\ufeff")
        or (os.environ.get("ACCESS_KEY_ID") or "").strip().strip("\ufeff")
    )
    secret = (
        (os.environ.get("AWS_SECRET_ACCESS_KEY") or "").strip().strip("\ufeff")
        or (os.environ.get("SECRET_ACCESS_KEY") or "").strip().strip("\ufeff")
    )
    if not (bucket and access and secret):
        return None
    endpoint = (
        (os.environ.get("AWS_S3_ENDPOINT_URL") or "").strip()
        or (os.environ.get("S3_ENDPOINT_URL") or "").strip()
        or (os.environ.get("ENDPOINT") or "").strip()
    )
    if not endpoint:
        if access.startswith("tid_"):
            endpoint = "https://t3.storage.dev"
        elif railway_bucket and bucket == railway_bucket:
            # Bucket name came from Railway's BUCKET — use Railway's S3 API host.
            endpoint = "https://storage.railway.app"
    region = (
        (os.environ.get("AWS_S3_REGION_NAME") or "").strip()
        or (os.environ.get("AWS_DEFAULT_REGION") or "").strip()
        or (os.environ.get("REGION") or "").strip()
    )
    if not region:
        region = "auto" if access.startswith("tid_") else "us-east-1"
    return {
        "bucket_name": bucket,
        "access_key": access,
        "secret_key": secret,
        "endpoint_url": endpoint or None,
        "region_name": region,
    }


_s3_object_storage_cfg = _s3_object_storage_config()
USE_S3_OBJECT_STORAGE = _s3_object_storage_cfg is not None

# Source docs + uploads (place files here or upload via API)
SYNDICATE_DATA_DIR = BASE_DIR / "data"
SYNDICATE_MAX_DOC_CHARS = 120_000

# Admin/API multipart uploads (Django default ~2.5MB can reject larger PDFs before the view runs).
_DATA_UPLOAD_MAX_MB = int((os.environ.get("DATA_UPLOAD_MAX_MB") or "32").strip() or "32")
DATA_UPLOAD_MAX_MEMORY_SIZE = max(2_621_440, _DATA_UPLOAD_MAX_MB * 1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE


# Application definition

_django_contrib = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS = []
if USE_CLOUDINARY:
    INSTALLED_APPS.append('cloudinary_storage')
INSTALLED_APPS.extend(_django_contrib)
if USE_CLOUDINARY:
    INSTALLED_APPS.append('cloudinary')
INSTALLED_APPS.extend(
    [
        'rest_framework',
        'rest_framework.authtoken',
        'corsheaders',
        'api',
        'apps.challenges.apps.ChallengesConfig',
    ]
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'syndicate_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'syndicate_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Local: SQLite (default). Production / Railway: set DATABASE_URL (Postgres plugin injects it),
# or set PGHOST + PGPORT + PGUSER + PGPASSWORD + PGDATABASE. Optional DATABASE_PUBLIC_URL
# is used if DATABASE_URL is empty (some templates expose only the public URL).


def _resolved_postgres_url() -> str | None:
    for key in ("DATABASE_URL", "DATABASE_PRIVATE_URL", "DATABASE_PUBLIC_URL"):
        v = (os.environ.get(key) or "").strip()
        if v:
            return v
    host = (os.environ.get("PGHOST") or "").strip()
    if not host:
        return None
    user = quote_plus((os.environ.get("PGUSER") or "").strip())
    password = quote_plus((os.environ.get("PGPASSWORD") or "").strip())
    database = (os.environ.get("PGDATABASE") or "").strip()
    port = (os.environ.get("PGPORT") or "5432").strip()
    if not database:
        return None
    return f"postgresql://{user}:{password}@{host}:{port}/{database}"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,
        },
    }
}

_pg_url = _resolved_postgres_url()
if _pg_url:
    import dj_database_url

    _ssl = (os.environ.get("DATABASE_SSL_REQUIRE") or "true").strip().lower() in (
        "1",
        "true",
        "yes",
    )
    DATABASES["default"] = dj_database_url.parse(
        _pg_url,
        conn_max_age=600,
        ssl_require=_ssl,
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
#
# Leading slash so /admin/ pages load CSS/JS from /static/... (not /admin/static/...).
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_ROOT.mkdir(parents=True, exist_ok=True)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Use plain StaticFilesStorage for collectstatic. WhiteNoise's CompressedStaticFilesStorage
    # post-process step can FileNotFoundError on Railway (admin Select2 i18n paths, etc.).
    # WhiteNoiseMiddleware still serves /static/ from STATIC_ROOT in production.
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# django-storages/boto3 require these setting names; traffic goes to AWS_S3_ENDPOINT_URL
# (e.g. Railway Bucket https://storage.railway.app — not necessarily Amazon AWS).
if USE_S3_OBJECT_STORAGE and _s3_object_storage_cfg:
    AWS_ACCESS_KEY_ID = _s3_object_storage_cfg["access_key"]
    AWS_SECRET_ACCESS_KEY = _s3_object_storage_cfg["secret_key"]
    AWS_STORAGE_BUCKET_NAME = _s3_object_storage_cfg["bucket_name"]
    AWS_S3_REGION_NAME = _s3_object_storage_cfg["region_name"]
    if _s3_object_storage_cfg.get("endpoint_url"):
        AWS_S3_ENDPOINT_URL = _s3_object_storage_cfg["endpoint_url"]
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = True
    # Private buckets: URLs from default_storage.url() are time-limited presigned GET links.
    AWS_QUERYSTRING_AUTH = True
    _presign = int((os.environ.get("PRESIGNED_URL_EXPIRE_SECONDS") or "3600").strip() or "3600")
    AWS_QUERYSTRING_EXPIRE = max(60, min(_presign, 604800))
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
    }
elif USE_CLOUDINARY:
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Admin superuser (production) ---
# Do not create users inside this file (it is imported on every request). Instead set:
#   DJANGO_SUPERUSER_EMAIL
#   DJANGO_SUPERUSER_PASSWORD
# Railway/docker: `railway_start.sh` runs `manage.py ensure_superuser` after migrate.

_cors_env = (os.environ.get("CORS_ALLOWED_ORIGINS") or "").strip()
if _cors_env:
    CORS_ALLOWED_ORIGINS = [x.strip() for x in _cors_env.split(",") if x.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

CORS_ALLOW_METHODS = ("DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT")

# DEBUG: allow Next.js (or any dev server) on any localhost port — avoids "Failed to fetch" when
# CORS_ALLOWED_ORIGINS is set to production-only in .env or when Next binds :3001, etc.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost(?::\d+)?$",
        r"^http://127\.0\.0\.1(?::\d+)?$",
    ]
else:
    CORS_ALLOWED_ORIGIN_REGEXES = []

_csrf_env = (os.environ.get("CSRF_TRUSTED_ORIGINS") or "").strip()
if _csrf_env:
    CSRF_TRUSTED_ORIGINS = [x.strip() for x in _csrf_env.split(",") if x.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

# Django admin login POST must match a trusted origin. Frontend-only CSRF vars omit the API
# hostname, which breaks /admin/ on Railway unless we add the public domain here too.
_rail_csrf = (os.environ.get("RAILWAY_PUBLIC_DOMAIN") or "").strip()
if _rail_csrf:
    _rail_origin = _rail_csrf if _rail_csrf.startswith("http") else f"https://{_rail_csrf}"
    _csrf_seen = {x.rstrip("/") for x in CSRF_TRUSTED_ORIGINS}
    if _rail_origin.rstrip("/") not in _csrf_seen:
        CSRF_TRUSTED_ORIGINS = [*CSRF_TRUSTED_ORIGINS, _rail_origin]
        _csrf_seen.add(_rail_origin.rstrip("/"))

# Trust the same hostnames you accept in ALLOWED_HOSTS (https), so /admin/ works even if
# RAILWAY_PUBLIC_DOMAIN is unset or you use a custom domain only listed in ALLOWED_HOSTS.
_csrf_seen = {x.rstrip("/") for x in CSRF_TRUSTED_ORIGINS}
for _host in ALLOWED_HOSTS:
    if _host in ("localhost", "127.0.0.1", "*", ""):
        continue
    _origin = _host if "://" in _host else f"https://{_host}"
    _key = _origin.rstrip("/")
    if _key not in _csrf_seen:
        CSRF_TRUSTED_ORIGINS = [*CSRF_TRUSTED_ORIGINS, _origin]
        _csrf_seen.add(_key)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "EXCEPTION_HANDLER": "api.exception_handlers.drf_json_exception_handler",
}

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Python 3.14+: Django 4.2's BaseContext.__copy__ used copy(super()), which breaks
# because super() is copyable in 3.14+ (Django #35844; fixed in Django 5.2+).
if sys.version_info >= (3, 14):
    from copy import copy as _copy_context_dicts

    from django.template.context import BaseContext as _BaseContext

    def _base_context_copy(self):
        duplicate = _BaseContext()
        duplicate.__class__ = self.__class__
        duplicate.__dict__ = _copy_context_dicts(self.__dict__)
        duplicate.dicts = self.dicts[:]
        return duplicate

    _BaseContext.__copy__ = _base_context_copy
